devops-s17-payments/payments

payments.py
added starter resource models (as dicts) for mvp. added http status codes. updated index function to display basic resource info.
=> update flask skeleton. resolves #28

payments.py
some refactoring to be done next sprint for this issue
=> Create add payment function. resolves #3

payments.py
uses DELTE /payments/{id} to delete the payment method.
=> added function of deleting payment method. resolves #8

payments.py, sampleData/sampleUpdateData.json
Should be modified next Sprint.
=> added the function of updating payments

payments.py, sampleData/samplePostData.json
payments can be now added to memory by passing json argument.
Remember to modify the content-type to application/json in the request header.
=> updata add payment method to work with json argument.

payments.py
set default payment will now handle deleted payments correctly
=> fix set default payment method.

Vagrantfile, payments.py
Docker container installed on vm. Tested on my machine.
Redis image is run in docker container. Will be tested later when developing using Redis.
=> Add code for building docker environment

payments.py
resolves #48 
also provides more general fix for handling Bad Request errors that were otherwise handled by flask default error handler
=> Fixing error check on add

payments.py
access via `/payments/charge`
uses PUT with json request body: `{'amount' : <float>}`
make sure you set headers to `Content-type` : `application/json` when testing
no need to specify index as this always targets default payment method.
=> Add charge action

payments.py
implement the is_valid function, also expand it.
=> expand the is_valid function

payments.py
We can query using the following URL:
http://localhost:5000/payments/query/?query-param=parameter-name&value=search-value
=> added query on different parameters

payments.py, sampleData/samplePartialUpdateData.json, sampleData/samplePostData.json, sampleData/sampleUpdateData.json
Add PATCH mehod for update payment partially
=> Finetune update payment

payments.py
switched to 'len(payments)-1' to ensure no out of bounds exceptions
=> fixed bug. was due to using 'current_payment_id' as index for success msg

payments.py
the final key to this operation was understanding how the query string works. it doesn't need be explicitly written in app.route, but is in fact a part of the request object, accesible via request.query_string
my fix checks route /payments and IF there is a query_string, we call the query_payments method
once called, we parse out the key:value pair and then (a) check if the key is valid then (b) check if the value for the key exists and if it does (c) add it to the results list. appropriate error messages sent as applicable.
NOTE: can only accommodate a single query at the moment. will be update next sprint.
=> got query working with URI payments?key:value

payments.py, sampleData/samplePostData.json
There is a logical error in if-else.  Fixed the bug. I think it works now.
=> fix the bug: cannot add a paypal payment

app/db/models.py
Fixes the incorrect import in `models.py`.
=> fix import in models

app/db/interface.py, app/payments.py, tests/test_error_handlers.py, tests/test_interface.py, tests/test_models.py, tests/test_payments.py
noticed this wasn't covered in the coverage report.
simple test to make sure index returns 200 and has 'Welcome to payments!'
This should be merged AFTER #123 as I was working off of that branch
=> Add index test

app/db/interface.py, tests/test_interface.py
added interface helper method to remove soft_deletes. updated tests re: same
=> FIXED : update get/query re: 'soft deletes'

app/db/__init__.py
not sure where we went wrong b/c i had my tables built, but i guess the code got lost during the refactor.
anyway, the few lines added in __init__.py of db module. this will fix the issue
=> actually inits db and creates tables

app/db/interface.py, app/payments.py, tests/test_interface.py, tests/test_payments.py
code refactored for the payment actions (charge and set default) and test cases have been written for both the interface.py as well as payments.py
Addresses issues: #93 #92 #131
=> Refactor payment actions

Vagrantfile, app/db/__init__.py, app/db/interface.py, app/payments.py, config.py, features/environment.py, features/payments.feature, features/steps/payment_steps.py, requirements.txt, tests/test_interface.py, tests/test_payments.py
added new features/steps folders. config basic environ setup/teardown added one 'home page' scenario just to make sure it works.
EDIT - includes new requirements so you'll need to `vagrant reload --provision`
=> bdd initial setup

Vagrantfile
you'll need to `vagrant reload --provision`
=> quick fix to add LOCAL_DB as vagrant machine env var

app/db/interface.py, tests/test_interface.py
=> catches [] and return error to be handled by crud get

app/db/interface.py
There was an undeclared `data` variable and also some usage of the `re` library without having it imported.  I resolved the most obvious problems that should hopefully save us runtime error woes, but there could still be logic errors.
=> Hotifx: is_valid_put

.behaverc, app/db/__init__.py, app/db/interface.py, tests/features/environment.py, tests/features/payments.feature, tests/features/steps/payment_steps.py, tests/test_interface.py
ok, so this issue revealed some interesting bugs. they are as follows:
**is_valid is a tad broken. my initial fixes for now:**
* all instances of variable `data` changed to `new_data`. both were used throughout the function, but were meant to represent the same dict
* missing `import re`
* i haven't quite figured out why yet, but the check for existing_user_id == data['user_id'] is failing when it shouldn't. i asserted in my put feature that those values are equal (and they are), but when the test hits that if statement in is_valid_put, it raises an Exception. i'll leave this to whomever ends up fixing `is_valid`. for now, that check has been commented out so we'll have to assume that a user won't try to pass another user's id when updating card info (with that in mind, maybe user_id …
=> Bdd update feature

.behaverc, app/db/__init__.py, app/db/interface.py, app/payments.py, tests/features/environment.py, tests/features/payments.feature, tests/features/steps/payment_steps.py, tests/test_interface.py
this should be merged after #159 as it builds from that branch.
simple test to set-default card and check that that card is now default
working on this uncovered an issue with the query which has been fixed and included in the bug PR ( #164 ).
=> Bdd set default feature

config.py, manifest.yml, tests/test_interface.py, tests/test_models.py
fixing up the changes i made. wasn't the fix i thought it might be. at least not yet.
=> restoring master to previous state

config.py, tests/test_interface.py, tests/test_models.py
trying to grab elephantsql uri instead of local test db
will restore when things break
=> testing bluemix once more

tests/features/environment.py
same fix worked for unit tests, hoping it will do the trick here as well
=> adding cloud/local check to bdd environ setup

tests/features/steps/payment_steps.py
Something got messed up during my rebase of my delete BDD branch.  I have uncommented parts of tests that needed to run in order to fix the issue.
=> Save BDD tests

tests/test_models.py
i noticed the coverage wasn't 100% in this test and found a duplicate test that was never being run (this the coverage loss).
=> removed duplicate test in test_models

tests/features/payments.feature, tests/features/steps/payment_steps.py
This PR adds a BDD scenario for the charge payment action.
=> Add BDD for charge payment action

tests/features/payments.feature, tests/features/steps/payment_steps.py
Added the following scenarios for double query
1. Querying using 2 parameters
2. Querying using 2 ids
3. Querying using 1 id and 1 parameter - to show id takes precedence
4. Querying using bad parameters(non existing values) returns 404
=> Bdd double query

app/payments.py, tests/features/payments.feature, tests/features/steps/payment_steps.py, tests/test_payments.py
Added feature to read payments - existing and non existing
modified the code in payments.py to show the proper error message (workaround for now)
=> Bdd read payments

tests/features/payments.feature, tests/features/steps/payment_steps.py
BDD feature for single query added (happy path and sad path)
=> bdd feature for single query

codecov.yml
payments#195: added codecov.yml file to ignore config.py and anything in tests/features/*
-trying to see if this increases the coverage
=> added codecov.yml file to ignore some files

codecov.yml
updated the path in the codecov file
=> corrected the path exp in codecov.yml

tests/test_interface.py, tests/test_models.py
i think the removal of these checks for testing broke the bluemix test env
=> it's really hot
